# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Generating Appsetting.json
  variables:
  - group: appsettings-generator
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'

  - script: pip install -r requirements.txt
    displayName: 'Install requirements'

  - script: |
    python jsongenerator/jsongenerator.py 
    displayName: 'Execute Python script'

  - script: jsongenerator/json/appsettings.json
    displayName: 'Check appsettings.json output'