trigger:
- master

stages:
- template: ./build-appsettings.yml  # Template reference
  parameters:
    pool: 'ubuntu-latest'
    target_spn: 'ntwairay-azure'
    azure_key_vault_url: $(AZURE_KEY_VAULT_URL)